### ISSUE TITLE
docker: intermittent FUSE issues

### ISSUE THREAD

**Issue by stapelberg** [distr1/distri#27]
This is pretty vague, but I have only used the docker container for a few minutes.

After some point, I could not start any programs anymore, it seemed like the FUSE file system was inaccessible.

Restarting the container fixed it.

**Comment by norpol** [comment]
If I start it, hit ctrl+c once I run into this issue

```bash
^C
ls
bash: /bin/ls: Transport endpoint is not connected
```

**Comment by stapelberg** [comment]
Ah! Thanks for that hint. I suppose signal propagation is broken.

**Comment by norpol** [comment]
updated the comment, figured out two different scenarios.

**Comment by stapelberg** [comment]
Yeah, looking at `ps` on the host, pressing ctrl+c definitely kills the fuse process. I think this is because we `exec` into bash. We should probably spawn bash and keep running, reaping zombies.

**Comment by norpol** [comment]
Ah ok, so for now just launching bash inside bash is a good workaround.

**Comment by stapelberg** [comment]
Pushed a fix. Try `docker pull distr1/distri:jackherer` and run again.
