### ISSUE TITLE
Comparison with existing projects

### ISSUE THREAD

**Issue by Jipok** [distr1/distri#40]
Do you know about Puppy, [Porteus](http://www.porteus.org) and [EasyOS](https://easyos.org/)?
Will you have something like EasyOS containers?

**Comment by stapelberg** [comment]
> Do you know about Puppy, [Porteus](http://www.porteus.org) and [EasyOS](https://easyos.org/)?

Thanks for the pointers. Yeah, there’s some overlap with each of these :)

> Will you have something like EasyOS containers?

No, containers are not currently something I’m interested in working on.

In general, I’m hesitant to add a comparison. We’re not trying to convince users to actually use distri, so I’m not sure who such a comparison would be for, and which particular aspects it should compare. Also, it’s perpetual work to keep it up-to-date.

I’ll close this issue for that reason, but do let me know if I’m missing something.
