### ISSUE TITLE
Live ISO for distri?

### ISSUE THREAD

**Issue by probonopd** [distr1/distri#42]
Is there a Live ISO for distri? It would be convenient for trying it out on real hardware without the need for installation.

**Comment by stapelberg** [comment]
There is only a live image, no installer.

Please follow https://distr1.org/#run-distri-on-real-hardware

**Comment by probonopd** [comment]
Thanks. Is it immutable like a real Live CD? I am looking for something to play around with that resets itself to the original clean state after each reboot. And ideally an ISO that I could throw on my SSD alongside all the other OSes.

[![](https://user-images.githubusercontent.com/2480569/32960053-e1b345d4-cbc3-11e7-9f34-c1cc11b5b1c7.png)](https://github.com/probonopd/SystemImageKit)

**Comment by stapelberg** [comment]
No, it’s mutable.

**Comment by probonopd** [comment]
Thanks. I am already downloading it. Still think a "real" live ISO would be an advantage.

**Comment by stapelberg** [comment]
If you want to reset, just write the image again? :)

**Comment by probonopd** [comment]
Yes, that's what I am doing now, but it still takes a dedicated USB drive. If I needed one for each of the OSes (and versions) I am keeping around, it'd easily go into the hundreds of drives.
