### ISSUE TITLE
internal/cp/copy.go: defer file.Close() confusion

### ISSUE THREAD

**Issue by h0tw4t3r** [distr1/distri#44]
Hey. I am a little confused in what is going on with deferring files closing in `internal/cp/copy.go`.

```
if err := out.Close(); err != nil {
	return err
}
```
Isn't it an extra call to [`out.Close()`](https://github.com/distr1/distri/blob/074e03dbafdb06432ea281348a8713bedd840e56/internal/cp/copy.go#L26) since we have [`defer out.Close()`](https://github.com/distr1/distri/blob/074e03dbafdb06432ea281348a8713bedd840e56/internal/cp/copy.go#L22)?

If it is not, and It's just me missing something with Go `defer` call handling, why there is no error check for [`defer in.Close()`](https://github.com/distr1/distri/blob/074e03dbafdb06432ea281348a8713bedd840e56/internal/cp/copy.go#L17)?

**Comment by stapelberg** [comment]
The deferred call is for avoiding resource leaks (we don’t care if it fails), the non-deferred call is for checking whether flushing the file to disk fails.

This is intentional :)
