### ISSUE TITLE
[Question] How will dkms be handled?

### ISSUE THREAD

**Issue by yshui** [distr1/distri#47]
Looks like /lib/modules is read-only, does that completely rule out things like dkms?

**Comment by stapelberg** [comment]
The concept of DKMS as a system to compile kernel-modules at installation time does not fit well into the distri philosophy.

Having out-of-tree kernel modules be built into packages does work, however (just not at installation time, i.e. in a third-party repo, or manually by the user). That package, once installed, will then provide paths within /lib/modules, just like other exchange directories do.

**Comment by yshui** [comment]
That does work. But I wonder how well would it scale once distri starts to include different versions of linux kernels (lts, different stable versions, etc.). Since then each out-of-tree module will have to be packaged for each of the different kernels.

Also this could make building custom kernels slightly harder.

**Comment by stapelberg** [comment]
> Since then each out-of-tree module will have to be packaged for each of the different kernels.

We are already in a similar situation with regards to rebuilding reverse dependencies after changing a package: we need to bump all packages affected by a change and rebuild them.

In general, distri favors a radically simple distribution model, and that requires tooling to make the approach viable in other places. For example, for the bumping I just mentioned, we have the `distri bump` command which does that automatically.

**Comment by yshui** [comment]
What kind of tooling do you think is needed to make creating kernel module packages easier? Or do you think it would be easy enough so it's not worth it?
