### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by mohe2015** [distr1/distri#56]
Hi,

for me the [torrent](https://repo.distr1.org/distri/jackherer/img/distri-qemu-serial.img.zst.torrent) doesn't work. It can't find any seeders (or how its called in english). Do you know if it is still supposed to work? Or is the seeder just offline?

**Comment by stapelberg** [comment]
Thanks for filing this.

For now, I have re-started the torrent client on my workstation, so you should be able to download from there.

Medium term, I’ll install a headless torrent seeder on my server.

**Comment by stapelberg** [comment]
Turns out there is a working torrent CLI client (with seeding functionality) written in Go, so that’s now deployed and should work regardless of what my workstation is up to :)
